from typing import Any, Dict, List, Optional, TypedDict


class AresState(TypedDict):
    # Always required
    original_task: str
    output_language: Optional[str]  # e.g. "Ukrainian", "English", "Polish"
    output_requirements: Optional[dict]
    image_settings: Optional[dict]
    qa_attempts: int
    execution_attempts: int
    run_id: str
    run_root_dir: str
    run_workspace_dir: str
    context_data_path: str
    asset_manifest_path: str
    downloaded_urls_path: str
    global_asset_index_path: str

    # Step / loop protection
    search_cycles: Optional[int]
    step_count: int
    max_steps: int

    # Supervisor / Core memory
    core_memory: Optional[List[str]]
    available_resources: Optional[Dict[str, Any]]
    asset_manifest: Optional[Dict[str, Any]]
    asset_manifest_summary: Optional[Dict[str, Any]]
    asset_requirements: Optional[List[str]]
    missing_image_queries: Optional[List[str]]
    accepted_asset_paths: Optional[List[str]]
    agent_needs: Optional[str]
    current_specialist: Optional[str]
    sub_task: Optional[str]
    completed: Optional[bool]
    next_node: Optional[str]

    # Agent pipeline fields
    current_plan: Optional[List[str]]
    gathered_info: Optional[str]
    current_agent_profile: Optional[dict]
    final_result: Optional[str]
    errors: Optional[List[str]]
    last_execution_error: Optional[str]
    needs_human_help: Optional[bool]
    clarifier_message: Optional[str]
    human_response: Optional[str]
    resolved_context: Optional[str]
    route_to_executor: Optional[bool]
    paused_by: Optional[str]
    replan_needed: Optional[bool]
    feedback_for_searcher: Optional[str]
    feedback_for_blacksmith: Optional[str]
    qa_passed: Optional[bool]

    # ── Multi-Agent Pipeline (AresAI 2.0) ──────────────────────────────────
    sub_agent_plan: Optional[List[Dict]]          # Ordered list of sub-agent tasks from Planner
    plan_needs_approval: Optional[bool]           # True після Planner
    plan_approved: Optional[bool]                 # True коли юзер натиснув Approve
    current_sub_agent_index: Optional[int]        # Index of the currently active sub-agent
    sub_agent_results: Optional[Dict[str, str]]   # task_id → result / output path

    # ── SkillRegistry (AresAI 3.0) ──────────────────────────────────────────
    skill_id: Optional[str]            # Skill ID for current sub-agent (matched in registry)
    skill_config: Optional[Dict]       # Config dict generated by Blacksmith for the skill
    raw_generated_code: Optional[str]  # Last generated code (feeds Code Doctor between retries)
